apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:    
      containers:
      - name: nodeapp
        image: ankushsatpute/ltidockerdemo
        imagePullPolicy: Always      
        ports:
        - containerPort: 8080
